export const STATION_CODES: Record<string, string> = {
  // Barcelona city
  PC:  'Pl. Catalunya',
  PR:  'Provença',
  GR:  'Gràcia',
  SG:  'Sant Gervasi',
  PD:  'Pàdua',
  EP:  'El Putxet',
  MN:  'Muntaner',
  BN:  'La Bonanova',
  TT:  'Les Tres Torres',
  PM:  'Pl. Molina',
  SR:  'Sarrià',
  RE:  'Reina Elisenda',
  TB:  'Av. Tibidabo',
  AV:  'Av. Tibidabo',
  PE:  'Pl. Espanya',
  MG:  'Magòria La Campana',
  IC:  'Ildefons Cerdà',
  GO:  'Gornal',
  SP:  'Sant Josep',
  LH:  'L\'Hospitalet Av. Carrilet',
  EU:  'Europa | Fira',

  // Vallès line (S1/S2)
  PF:  'Peu del Funicular',
  VR:  'Vallvidrera Inferior',
  VS:  'Vallvidrera Superior',
  VL:  'Baixador de Vallvidrera',
  LF:  'La Floresta',
  VD:  'Valldoreix',
  SC:  'Sant Cugat',
  MS:  'Mira-Sol',
  VO:  'Volpelleres',
  SJ:  'Sant Joan',
  BT:  'Bellaterra',
  UN:  'Universitat Autònoma',
  UA:  'Universitat Autònoma',
  HG:  'Hospital General',
  RB:  'Rubí Centre',
  FN:  'Les Fonts',
  TR:  'Terrassa - Rambla',
  VP:  'Vallparadís Universitat',
  EN:  'Terrassa Estació del Nord',
  TE:  'Terrassa Est',
  NA:  'Terrassa Nacions Unides',
  TN:  'Terrassa Nacions Unides',
  CF:  'Can Feu - Gràcia',
  CT:  'La Creu Alta',
  PJ:  'Sabadell Plaça Major',
  NO:  'Sabadell Nord',
  PN:  'Sabadell Parc del Nord',
  SPF: 'Sabadell Parc del Nord',
  SQ:  'Sant Quirze',

  // Llobregat-Anoia (R5/R6/L8/S4/S8)
  AL:  'Almeda',
  CO:  'Cornellà Riera',
  BO:  'Sant Boi',
  SB:  'Sant Boi',
  CL:  'Santa Coloma de Cervelló',
  CG:  'Colònia Güell',
  CR:  'Can Ros',
  QC:  'Quatre Camins',
  PA:  'Pallejà',
  SA:  'Sant Andreu de la Barca',
  PL:  'El Palau',
  MV:  'Martorell Vila',
  MC:  'Martorell Central',
  ME:  'Martorell Enllaç',
  AB:  'Abrera',
  OL:  'Olesa de Montserrat',
  AE:  'Montserrat-Aeri',
  MO:  'Monistrol de Montserrat',
  MP:  'Monistrol-Vila',
  SV:  'Sant Vicenç-Castellgalí',
  VI:  'Manresa Viladordis',
  MA:  'Manresa-Alta',
  MB:  'Manresa-Baixador',
  MBI: 'Manresa Baixador',
  SE:  'Sant Esteve Sesrovires',
  BE:  'La Beguda',
  CP:  'Can Parellada',
  MQ:  'Masquefa',
  PI:  'Piera',
  VA:  'Vallbona d\'Anoia',
  CA:  'Capellades',
  PO:  'La Pobla de Claramunt',
  VN:  'Vilanova del Camí',
  IG:  'Igualada',
  ML:  'Molí Nou - Ciutat Cooperativa',
  MN1: 'Molí Nou - Ciutat Cooperativa',
  VH:  'Sant Vicenç dels Horts',
  VH1: 'Sant Vicenç dels Horts',

  // Cremallera / Funicular
  MM:  'Montserrat',
  FV:  'Funicular de Vallvidrera',

  // Lleida-La Pobla
  LE:  'Lleida',
  AT:  'Alcoletge',
  VB:  'Vilanova de la Barca',
  VF:  'Vallfogona de Balaguer',
  BG:  'Balaguer',
  SM:  'St. Llorenç de Montgai',
  LS:  'Vilanova de la Sal',
  AR:  'Àger',
  LL:  'Cellers-Llimiana',
  GT:  'Guardia de Tremp',
  PT:  'Palau de Noguera',
  TP:  'Tremp',
  SD:  'Salàs de Pallars',
  PS:  'La Pobla de Segur',

  // Núria
  NU:  'Núria',
  QUE: 'Queralbs',
  RR:  'Ribes-Enllaç',
}

export const LINE_COLORS: Record<string, string> = {
  L6:  '#797FBC',
  L7:  '#B2600B',
  L8:  '#E274AA',
  L12: '#b2aed3',
  S1:  '#EF7900',
  S2:  '#88BB0B',
  S3:  '#4F868E',
  S4:  '#A78600',
  S8:  '#49C0DE',
  S9:  '#DF4661',
  R5:  '#3dbfc3',
  R6:  '#b3b3b3',
  R50: '#00738a',
  R53: '#3dbfc3',
  R60: '#5b5b5b',
  R63: '#b3b3b3',
  RL1: '#FF8000',
  RL2: '#FF8000',
  FV:  '#0A57A3',
  MM:  '#000000',
  L1:  '#000000',
}

// Car codes of an FGC 4-car unit in physical composition order — M1 (cab
// motor), M2 (its inseparable pair), then the intermediates — matching the
// order fetchTrains() emits Train.wagons.
export const WAGON_LABELS = ['M1', 'M2', 'Mi', 'Ri']
